// vue-frontend/src/components/MemberTile.vue
<script setup lang="ts">
import { type Member } from '../interfaces/Member';

const props = defineProps<{
  member: Member;
  shortImage?: boolean;
}>();

const handleMemberClick = () => {
  // navigate(`/member/${member.id}`);
};

</script>

<template>
  <div class="flex flex-col justify-between gap-2 border border-slate-500 p-2 rounded-md cursor-pointer" :class="{
    'w-fit': !shortImage,
  }" @click="handleMemberClick">
    <img :src="props.member.image.url" class="w-full rounded-lg" :class="{ 'h-28': shortImage, 'h-52': !shortImage }" />
    <div className='flex flex-col gap-1'>
      <p>
        name: <span>{{ member.name }}</span>
      </p>
      <p>
        Defaulter: <span>{{ member.isDefaulter ? 'True' : 'False' }}</span>
      </p>
      <p>
        Monthly Subscribed:{' '}
        <span>{{ member.isMonthlySubscribed ? 'True' : 'False' }}</span>
      </p>
    </div>
  </div>
</template>

// frontend/src/components/MemberTile.tsx
import React from 'react';
import { Member } from '../interfaces/Member';
import { useNavigate } from 'react-router-dom';

interface MemberTileProps {
  member: Member;
  shortImage?: boolean;
}

const MemberTile: React.FC<MemberTileProps> = ({ member, shortImage }) => {
  const navigate = useNavigate();

  const handleMemberClick = () => {
    navigate(`/member/${member.id}`);
  };

  return (
    <div
      className={` ${
        shortImage ? 'w-fit' : ''
      } flex flex-col justify-between gap-2 border border-slate-500 p-2 rounded-md cursor-pointer`}
      onClick={handleMemberClick}
    >
      <img
        src={member.image.url}
        className={`${shortImage ? 'h-28' : 'h-52'} w-full rounded-lg`}
      />
      <div className='flex flex-col gap-1'>
        <p>
          name: <span>{member.name}</span>
        </p>
        <p>
          Defaulter: <span>{member.isDefaulter ? 'True' : 'False'}</span>
        </p>
        <p>
          Monthly Subscribed:{' '}
          <span>{member.isMonthlySubscribed ? 'True' : 'False'}</span>
        </p>
      </div>
    </div>
  );
};

export default MemberTile;
