// frontend/src/pages/Home.tsx
import { useEffect, useState } from 'react';
import RadioSection from '../components/RadioSection';
import { getData } from '../api/GET';
import { Book } from '../interfaces/Book';
import BookTile from '../components/BookTile';
import { Member } from '../interfaces/Member';
import MemberTile from '../components/MemberTile';
import { AiOutlineArrowRight, AiOutlineArrowLeft } from 'react-icons/ai';
import useBookModal from '../hooks/useBookModal';
import useMemberModal from '../hooks/useMemberModal';
import BookModal from '../components/modals/BookModal';
import MemberModal from '../components/modals/MemberModal';

const Home = () => {
  const [data, setData] = useState([]);
  const [radioOption, setRadioOption] = useState('books');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(0);

  const bookModal = useBookModal();
  const memberModal = useMemberModal();

  const fetchData = async (type: string) => {
    const response = await getData(type, page);
    setData(response);

    if (response.length < 10) {
      setTotalPages(page);
    } else {
      setTotalPages(page + 1);
    }
  };

  useEffect(() => {
    fetchData(radioOption);
  }, [page]);

  const onStateChange = (e: any) => {
    setRadioOption(e.target.value);
    fetchData(e.target.value);
  };

  const onNextClick = () => {
    setPage(page + 1);
  };

  const onPrevClick = () => {
    setPage(page - 1);
  };

  return (
    <div>
      <BookModal refetchData={() => fetchData('books')} />
      <MemberModal />
      <RadioSection radioOption={radioOption} onChange={onStateChange} />
      {/* Filters Here later */}

      <div className='flex gap-5 p-5 mt-5 rounded-md justify-center'>
        <button
          className='p-2 bg-purple-500 hover:bg-purple-700 text-white rounded-md'
          onClick={() => bookModal.onOpen()}
        >
          Create/Update Book
        </button>
        <button
          className='p-2 bg-purple-500 hover:bg-purple-700 text-white rounded-md'
          onClick={() => memberModal.onOpen()}
        >
          Create/Update Member
        </button>
      </div>

      {!data.length && (
        <div className='mt-5 flex justify-center items-center p-2 text-2xl w-full'>
          Nothing to show!
        </div>
      )}

      <div className='p-5 grid grid-col-1 sm:grip-col-2 md:grid-col-3 lg:grid-cols-4 xl:grid-cols-4 gap-16'>
        {data.length &&
          (radioOption === 'books'
            ? data?.map((book: Book) => {
                return <BookTile key={book.id} book={book} />;
              })
            : data?.map((member: Member) => {
                return <MemberTile key={member.id} member={member} />;
              }))}
      </div>

      <div className='flex justify-end gap-6 mt-2 p-6'>
        <div
          className={`flex justify-center items-center gap-1 ${
            page === 1 ? 'pointer-events-none opacity-60' : 'cursor-pointer'
          }`}
          onClick={onPrevClick}
        >
          <AiOutlineArrowLeft className='text-red-500' size={25} /> <p>Prev</p>
        </div>
        <div
          className={`flex justify-center items-center gap-1 cursor-pointer ${
            page >= totalPages
              ? 'pointer-events-none opacity-60'
              : 'cursor-pointer'
          }`}
          onClick={onNextClick}
        >
          <p>Next</p>
          <AiOutlineArrowRight className='text-red-500' size={25} />
        </div>
      </div>
    </div>
  );
};

export default Home;

// vue-frontend/src/views/Home.vue
<script lang="ts" setup>
import { ref, watch } from 'vue';
import { useModalStore } from '../stores/modal';
import BookModal from '../components/modals/BookModal.vue';
import MemberModal from '../components/modals/MemberModal.vue';
import { useLoaderStore } from '../stores/loader';
import Loader from '../components/Loader.vue';
import RadioSection from '../components/RadioSection.vue';
import { getData } from '../api/GET';

const data = ref([]);
const radioOption = ref('books');
const page = ref(1);
const totalPages = ref(0);

const { activeModal, openModal } = useModalStore();
const { isLoaderSpinning, onLoaderOpen, onLoaderClose } = useLoaderStore();

const fetchData = async (type: string) => {
  onLoaderOpen();
  const response = await getData(type, page.value);
  data.value = response;

  // TODO: Need to test if this is working or not.
  if (response?.length < 10) {
    // @ts-ignore
    totalPages.value(page.value);
  } else {
    // @ts-ignore
    totalPages.value(page.value + 1);
  }
  
  onLoaderClose();
};

const refetchData = () => fetchData(activeModal!);

watch(page, () => {
  fetchData(radioOption.value);
});

const onStateChange = (e: any) => {
  radioOption.value = e.target.value;
  fetchData(e.target.value);
};

const onNextClick = () => {
  page.value = page.value + 1;
};

const onPrevClick = () => {
  page.value = page.value - 1;
};
</script>

<template>
  <div>
    <Loader :visible="isLoaderSpinning" />
    <BookModal v-if="activeModal && activeModal === 'book'" :refetch-data="refetchData" />
    <MemberModal v-if="activeModal && activeModal === 'member'" :refetch-data="refetchData" />
    <RadioSection :radioOption="radioOption" :onChange="onStateChange" />
    
      <!-- Filters Here later -->

    <div class="flex gap-5 p-5 mt-5 rounded-md justify-center">
      <button
        class="p-2 bg-purple-500 hover:bg-purple-700 text-white rounded-md"
        @click="openModal('book')"
      >
        Create/Update Book
      </button>
      <button
        class="p-2 bg-purple-500 hover:bg-purple-700 text-white rounded-md"
        @click="openModal('member')"
      >
        Create/Update Member
      </button>
    </div>

    <template v-if="!data.length">
      <div class="mt-5 flex justify-center items-center p-2 text-2xl w-full">
        Nothing to show!
      </div>
    </template>

    <div
      class="p-5 grid grid-col-1 sm:grip-col-2 md:grid-col-3 lg:grid-cols-4 xl:grid-cols-4 gap-16"
    >
      <template v-if="data.length">
        <template v-for="item in data">
          <div v-if="radioOption === 'books'">
            <!-- @vue-ignore -->
            <BookTile :key="item.id" :book="item" />
          </div>
          <div v-else>
            <!-- @vue-ignore -->
            <MemberTile :key="item.id" :member="item" />
          </div>
        </template>
      </template>
    </div>

    <div class="flex justify-end gap-6 mt-2 p-6">
      <div
        class="flex justify-center items-center gap-1"
        :class="{
          'pointer-events-none opacity-60': page === 1,
          'cursor-pointer': page > 1,
        }"
        @click="onPrevClick"
      >
        <AiOutlineArrowLeft class="text-red-500" size="{25}" />
        <p>Prev</p>
      </div>
      <div
        class="flex justify-center items-center gap-1 cursor-pointer"
        :class="{
          'pointer-events-none opacity-60': page >= totalPages,
          'cursor-pointer': page < totalPages,
        }"
        @click="onNextClick"
      >
        <p>Next</p>
        <AiOutlineArrowRight class="text-red-500" size="{25}" />
      </div>
    </div>
  </div>
</template>
