// vue-frontend/src/components/RadioSection.vue
<script setup lang="ts">
const props = defineProps<{
  radioOption: String,
  onChange: (e: any) => void
}>();

const handleChange = (e: any) => {
      props.onChange(e);
}

</script>

<template>
    <div className='flex justify-around mt-2'>
      <div className='flex gap-2'>
        <input type="radio" id="one" value="book" v-model="props.radioOption" @change="handleChange" />
        <label id='bookLabel' for="bookLabel">BOOK</label>
      </div>
      <div className='flex gap-2'>
        <input type="radio" id="two" value="member" v-model="props.radioOption" @change="handleChange" />
        <label id='memberLabel' for="memberLabel">MEMBER</label>
      </div>
    </div>
</template>

// react-frontend/src/components/RadioSection.tsx
interface RadioSectionProps {
  radioOption: string;
  onChange: (e: any) => void;
}

const RadioSection: React.FC<RadioSectionProps> = ({radioOption, onChange}) => {
  return (
    <div className='flex justify-around mt-2'>
      <div className='flex gap-2'>
        <input type='radio' checked={radioOption === "books"}  value='books' onChange={(e: any) => onChange(e)} />
        <label id='bookLabel'>BOOK</label>
      </div>
      <div className='flex gap-2'>
        <input type='radio' checked={radioOption === "members"} value='members' onChange={(e: any) => onChange(e)}/>
        <label id='memberLable'>MEMBER</label>
      </div>
    </div>
  );
};

export default RadioSection;
